version: '3.8'

services:
  military-chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS:-https://smart.ibrahimshaikh.com.tr,http://localhost:3000,http://localhost:8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_TO_FILE=${LOG_TO_FILE:-false}
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database
      - ./documents:/app/documents
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - default

networks:
  default:
    driver: bridge
